"""Changed Task ID column

Revision ID: 12ace9122c6e
Revises: bbc1c6589ef6
Create Date: 2023-07-25 14:49:56.554935+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12ace9122c6e'
down_revision = 'bbc1c6589ef6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
