"""Removed backpopulates from Task owner table

Revision ID: bbc1c6589ef6
Revises: fc1681ed16ad
Create Date: 2023-07-25 14:38:11.951546+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bbc1c6589ef6'
down_revision = 'fc1681ed16ad'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
